DROP DATABASE IF EXISTS amnesty_db;
CREATE DATABASE amnesty_db DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
USE amnesty_db;

DROP TABLE IF EXISTS countries;
CREATE TABLE countries (
id int(11) not null auto_increment,
country varchar(100) not null,
country_abr varchar(3) not null,
primary key(id)
)engine=innodb;

INSERT INTO countries (id, country, country_abr) VALUES
(NULL, 'Afghanistan', 'AFG'),
(NULL, 'Åland Islands', 'ALA'),
(NULL, 'Albania', 'ALB'),
(NULL, 'Algeria', 'DZA'),
(NULL, 'American Samoa', 'ASM'),
(NULL, 'Andorra', 'AND'),
(NULL, 'Angola', 'AGO'),
(NULL, 'Anguilla', 'AIA'),
(NULL, 'Antarctica', 'ATA'),
(NULL, 'Antigua and Barbuda', 'ATG'),
(NULL, 'Argentina', 'ARG'),
(NULL, 'Armenia', 'ARM'),
(NULL, 'Aruba', 'ABW'),
(NULL, 'Australia', 'AUS'),
(NULL, 'Austria', 'AUT'),
(NULL, 'Azerbaijan', 'AZE'),
(NULL, 'Bahamas', 'BHS'),
(NULL, 'Bahrain', 'BHR'),
(NULL, 'Bangladesh', 'BGD'),
(NULL, 'Barbados', 'BRB'),
(NULL, 'Belarus', 'BLR'),
(NULL, 'Belgium', 'BEL'),
(NULL, 'Belize', 'BLZ'),
(NULL, 'Benin', 'BEN'),
(NULL, 'Bermuda', 'BMU'),
(NULL, 'Bhutan', 'BTN'),
(NULL, 'Bolivia, Plurinational State of', 'BOL'),
(NULL, 'Bonaire, Sint Eustatius and Saba', 'BES'),
(NULL, 'Bosnia and Herzegovina', 'BIH'),
(NULL, 'Botswana', 'BWA'),
(NULL, 'Bouvet Island', 'BVT'),
(NULL, 'Brazil', 'BRA'),
(NULL, 'British Indian Ocean Territory', 'IOT'),
(NULL, 'Brunei Darussalam', 'BRN'),
(NULL, 'Bulgaria', 'BGR'),
(NULL, 'Burkina Faso', 'BFA'),
(NULL, 'Burundi', 'BDI'),
(NULL, 'Cambodia', 'KHM'),
(NULL, 'Cameroon', 'CMR'),
(NULL, 'Canada', 'CAN'),
(NULL, 'Cape Verde', 'CPV'),
(NULL, 'Cayman Islands', 'CYM'),
(NULL, 'Central African Republic', 'CAF'),
(NULL, 'Chad', 'TCD'),
(NULL, 'Chile', 'CHL'),
(NULL, 'China', 'CHN'),
(NULL, 'Christmas Island', 'CXR'),
(NULL, 'Cocos (Keeling) Islands', 'CCK'),
(NULL, 'Colombia', 'COL'),
(NULL, 'Comoros', 'COM'),
(NULL, 'Congo', 'COG'),
(NULL, 'Congo, the Democratic Republic of the', 'COD'),
(NULL, 'Cook Islands', 'COK'),
(NULL, 'Costa Rica', 'CRI'),
(NULL, 'Côte d’Ivoire', 'CIV'),
(NULL, 'Croatia', 'HRV'),
(NULL, 'Cuba', 'CUB'),
(NULL, 'Curaçao', 'CUW'),
(NULL, 'Cyprus', 'CYP'),
(NULL, 'Czech Republic', 'CZE'),
(NULL, 'Denmark', 'DNK'),
(NULL, 'Djibouti', 'DJI'),
(NULL, 'Domenica', 'DMA'),
(NULL, 'Dominican RepDominicaublic', 'DOM'),
(NULL, 'Ecuador', 'ECU'),
(NULL, 'Egypt', 'EGY'),
(NULL, 'El Salvador', 'SLV'),
(NULL, 'Equatorial Guinea', 'GNQ'),
(NULL, 'Eritrea', 'ERI'),
(NULL, 'Estonia', 'EST'),
(NULL, 'Ethiopia', 'ETH'),
(NULL, 'Falkland Islands (Malvinas)', 'FLK'),
(NULL, 'Faroe Islands', 'FRO'),
(NULL, 'Fiji', 'FJI'),
(NULL, 'Finland', 'FIN'),
(NULL, 'France', 'FRA'),
(NULL, 'French Guiana', 'GUF'),
(NULL, 'French Polynesia', 'PYF'),
(NULL, 'French Southern Territories', 'ATF'),
(NULL, 'Gabon', 'GAB'),
(NULL, 'Gambia', 'GMB'),
(NULL, 'Georgia', 'GEO'),
(NULL, 'Germany', 'DEU'),
(NULL, 'Ghana', 'GHA'),
(NULL, 'Gibraltar', 'GIB'),
(NULL, 'Greece', 'GRC'),
(NULL, 'Greenland', 'GRL'),
(NULL, 'Grenada', 'GRD'),
(NULL, 'Guadeloupe', 'GLP'),
(NULL, 'Guam', 'GUM'),
(NULL, 'Guatemala', 'GTM'),
(NULL, 'Guernsey', 'GGY'),
(NULL, 'Guinea', 'GIN'),
(NULL, 'Guinea-Bissau', 'GNB'),
(NULL, 'Guyana', 'GUY'),
(NULL, 'Haiti', 'HTI'),
(NULL, 'Heard Island and McDonald Islands', 'HMD'),
(NULL, 'Holy See (Vatican City State)', 'VAT'),
(NULL, 'Honduras', 'HND'),
(NULL, 'Hong Kong', 'HKG'),
(NULL, 'Hungary', 'HUN'),
(NULL, 'Iceland', 'ISL'),
(NULL, 'India', 'IND'),
(NULL, 'Indonesia', 'IDN'),
(NULL, 'Iran, Islamic Republic of', 'IRN'),
(NULL, 'Iraq', 'IRQ'),
(NULL, 'Ireland', 'IRL'),
(NULL, 'Isle of Man', 'IMN'),
(NULL, 'Israel', 'ISR'),
(NULL, 'Italy', 'ITA'),
(NULL, 'Jamaica', 'JAM'),
(NULL, 'Japan', 'JPN'),
(NULL, 'Jersey', 'JEY'),
(NULL, 'Jordan', 'JOR'),
(NULL, 'Kazakhstan', 'KAZ'),
(NULL, 'Kenya', 'KEN'),
(NULL, 'Kiribati', 'KIR'),
(NULL, 'Korea, Democratic People’s Republic of', 'PRK'),
(NULL, 'Korea, Republic of', 'KOR'),
(NULL, 'Kuwait', 'KWT'),
(NULL, 'Kyrgyzstan', 'KGZ'),
(NULL, 'Lao People’s Democratic Republic', 'LAO'),
(NULL, 'Latvia', 'LVA'),
(NULL, 'Lebanon', 'LBN'),
(NULL, 'Lesotho', 'LSO'),
(NULL, 'Liberia', 'LBR'),
(NULL, 'Libya', 'LBY'),
(NULL, 'Liechtenstein', 'LIE'),
(NULL, 'Lithuania', 'LTU'),
(NULL, 'Luxembourg', 'LUX'),
(NULL, 'Macao', 'MAC'),
(NULL, 'Macedonia, the former Yugoslav Republic of', 'MKD'),
(NULL, 'Madagascar', 'MDG'),
(NULL, 'Malawi', 'MWI'),
(NULL, 'Malaysia', 'MYS'),
(NULL, 'Maldives', 'MDV'),
(NULL, 'Mali', 'MLI'),
(NULL, 'Malta', 'MLT'),
(NULL, 'Marshall Islands', 'MHL'),
(NULL, 'Martinique', 'MTQ'),
(NULL, 'Mauritania', 'MRT'),
(NULL, 'Mauritius', 'MUS'),
(NULL, 'Mayotte', 'MYT'),
(NULL, 'Mexico', 'MEX'),
(NULL, 'Micronesia, Federated States of', 'FSM'),
(NULL, 'Moldova, Republic of', 'MDA'),
(NULL, 'Monaco', 'MCO'),
(NULL, 'Mongolia', 'MNG'),
(NULL, 'Montenegro', 'MNE'),
(NULL, 'Montserrat', 'MSR'),
(NULL, 'Morocco', 'MAR'),
(NULL, 'Mozambique', 'MOZ'),
(NULL, 'Myanmar', 'MMR'),
(NULL, 'Namibia', 'NAM'),
(NULL, 'Nauru', 'NRU'),
(NULL, 'Nepal', 'NPL'),
(NULL, 'Netherlands', 'NLD'),
(NULL, 'New Caledonia', 'NCL'),
(NULL, 'New Zealand', 'NZL'),
(NULL, 'Nicaragua', 'NIC'),
(NULL, 'Niger', 'NER'),
(NULL, 'Nigeria', 'NGA'),
(NULL, 'Niue', 'NIU'),
(NULL, 'Norfolk Island', 'NFK'),
(NULL, 'Northern Mariana Islands', 'MNP'),
(NULL, 'Norway', 'NOR'),
(NULL, 'Oman', 'OMN'),
(NULL, 'Pakistan', 'PAK'),
(NULL, 'Palau', 'PLW'),
(NULL, 'Palestinian Territory, Occupied', 'PSE'),
(NULL, 'Panama', 'PAN'),
(NULL, 'Papua New Guinea', 'PNG'),
(NULL, 'Paraguay', 'PRY'),
(NULL, 'Peru', 'PER'),
(NULL, 'Philippines', 'PHL'),
(NULL, 'Pitcairn', 'PCN'),
(NULL, 'Poland', 'POL'),
(NULL, 'Portugal', 'PRT'),
(NULL, 'Puerto Rico', 'PRI'),
(NULL, 'Qatar', 'QAT'),
(NULL, 'Réunion', 'REU'),
(NULL, 'Romania', 'ROU'),
(NULL, 'Russian Federation', 'RUS'),
(NULL, 'Rwanda', 'RWA'),
(NULL, 'Saint Barthélemy', 'BLM'),
(NULL, 'Saint Helena, Ascension and Tristan da Cunha', 'SHN'),
(NULL, 'Saint Kitts and Nevis', 'KNA'),
(NULL, 'Saint Lucia', 'LCA'),
(NULL, 'Saint Martin (French part)', 'MAF'),
(NULL, 'Saint Pierre and Miquelon', 'SPM'),
(NULL, 'Saint Vincent and the Grenadines', 'VCT'),
(NULL, 'Samoa', 'WSM'),
(NULL, 'San Marino', 'SMR'),
(NULL, 'Sao Tome and Principe', 'STP'),
(NULL, 'Saudi Arabia', 'SAU'),
(NULL, 'Senegal', 'SEN'),
(NULL, 'Serbia', 'SRB'),
(NULL, 'Seychelles', 'SYC'),
(NULL, 'Sierra Leone', 'SLE'),
(NULL, 'Singapore', 'SGP'),
(NULL, 'Sint Maarten (Dutch part)', 'SXM'),
(NULL, 'Slovakia', 'SVK'),
(NULL, 'Slovenia', 'SVN'),
(NULL, 'Solomon Islands', 'SLB'),
(NULL, 'Somalia', 'SOM'),
(NULL, 'South Africa', 'ZAF'),
(NULL, 'South Georgia and the South Sandwich Islands', 'SGS'),
(NULL, 'South Sudan', 'SSD'),
(NULL, 'Spain', 'ESP'),
(NULL, 'Sri Lanka', 'LKA'),
(NULL, 'Sudan', 'SDN'),
(NULL, 'Suriname', 'SUR'),
(NULL, 'Svalbard and Jan Mayen', 'SJM'),
(NULL, 'Swaziland', 'SWZ'),
(NULL, 'Sweden', 'SWE'),
(NULL, 'Switzerland', 'CHE'),
(NULL, 'Syrian Arab Republic', 'SYR'),
(NULL, 'Taiwan, Province of China', 'TWN'),
(NULL, 'Tajikistan', 'TJK'),
(NULL, 'Tanzania, United Republic of', 'TZA'),
(NULL, 'Thailand', 'THA'),
(NULL, 'Timor-Leste', 'TLS'),
(NULL, 'Togo', 'TGO'),
(NULL, 'Tokelau', 'TKL'),
(NULL, 'Tonga', 'TON'),
(NULL, 'Trinidad and Tobago', 'TTO'),
(NULL, 'Tunisia', 'TUN'),
(NULL, 'Turkey', 'TUR'),
(NULL, 'Turkmenistan', 'TKM'),
(NULL, 'Turks and Caicos Islands', 'TCA'),
(NULL, 'Tuvalu', 'TUV'),
(NULL, 'Uganda', 'UGA'),
(NULL, 'Ukraine', 'UKR'),
(NULL, 'United Arab Emirates', 'ARE'),
(NULL, 'United Kingdom', 'GBR'),
(NULL, 'United States', 'USA'),
(NULL, 'United States Minor Outlying Islands', 'UMI'),
(NULL, 'Uruguay', 'URY'),
(NULL, 'Uzbekistan', 'UZB'),
(NULL, 'Vanuatu', 'VUT'),
(NULL, 'Venezuela, Bolivarian Republic of', 'VEN'),
(NULL, 'Viet Nam', 'VNM'),
(NULL, 'Virgin Islands, British', 'VGB'),
(NULL, 'Virgin Islands, U.S.', 'VIR'),
(NULL, 'Wallis and Futuna', 'WLF'),
(NULL, 'Western Sahara', 'ESH'),
(NULL, 'Yemen', 'YEM'),
(NULL, 'Zambia', 'ZMB'),
(NULL, 'Zimbabwe', 'ZWE');

DROP TABLE IF EXISTS users;
CREATE TABLE users (
id int(11) not null auto_increment,
first_name varchar(80) not null,
last_name varchar(80) not null,
email varchar(40) not null,
phone varchar (30) not null,
country_id int(11) not null,
primary key(id),
foreign key(country_id) references countries(id) on update cascade on delete cascade
)engine=innodb;

DROP TABLE IF EXISTS messages;
CREATE TABLE messages (
user_id int(11) not null,
message text not null,
sent_at timestamp not null,
primary key(user_id, sent_at),
foreign key(user_id) references users(id) on update cascade on delete cascade 
)engine=innodb;



